// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import SearchController from "./search_controller.js"
application.register("search", SearchController)

import TesteController from "./teste_controller"
application.register("teste", TesteController)
